---
title: "Selected Publications"
author: "Michael Asher"
date: "`r format(Sys.Date())`"
output:
  html_document:
    df_print: paged
# layout: single
layout: standard # standard or wide-body
show_title_as_headline: false
---

# Preprints

Carvalho, P.F., **Asher, M. W.**, Sana, F. & Koedinger, K. R. (under review). Skip the reading assignment: Effective and efficient learning with only practice and feedback. https://osf.io/preprints/osf/9y2tb

# 2026

**Asher, M. W.**, Gold, G., Chen, E., & Carvalho, P.F. (in press). Chatbots are undermining crowdsourced research in the behavioral sciences: Detecting AI-assisted cheating with a keystroke-based tool. *Advances in Methods and Practices in Psychological Science* https://doi.org/10.31219/osf.io/a3pzx_v1

**Asher, M. W.**, & Carvalho, P.F. (2026). Conditions for effective learning without upfront instruction: How practice with feedback supports memory, generalization, motivation, and metacognition. *Educational Psychology Review* https://doi.org/10.1007/s10648-025-10103-6 [[pdf]](/publications/asher_et_al_2026_edpr.pdf)

# 2025

**Asher, M. W.**, Kwon, C., Stamper, J., Ogan, A., & Carvalho, P. F. (2025). Validating a new approach for measuring student engagement in remote, low-infrastructure learning environments. *Proceedings of the 2025 ACM Conference on Learning at Scale.* https://doi.org/10.1145/3698205.3729556 **Best Paper Award**

**Asher, M. W.**, Hartman, J. D., Blaser, M., Eichler, J. F., & Carvalho, P. F. (2025). The promise of mastery-based testing for promoting student engagement, self-regulated learning, and performance in gateway STEM courses. *Computers & Education* https://doi.org/10.1016/j.compedu.2025.105387 [[pdf]](/publications/asher_et_al_2025_ce.pdf)

**Asher, M. W.**, Hecht, C. A., Harackiewicz, J. M., Curtin, J. J., Parrisius, C., & Nagengast, B.  (in press). Why elusive expectancy × value interactions may be critical for theory and
intervention: A simulated power analysis. *Motivation Science.* [[pdf]](/publications/asher_et_al_inpress_motsci.pdf)

**Asher, M. W.**, Sana, F., Koedinger, K. R., & Carvalho, P. F. (2025). Practice with feedback vs. lecture: Consequences for learning, efficiency, and motivation. *Journal of Applied Research in Memory and Cognition.* https://doi.org/10.31234/osf.io/kft8u [[pdf]](/publications/asher_et_al_2025_jarmac.pdf)

# 2024

**Asher, M. W.**, & Harackiewicz, J. M. (2024). Using utility value and choice to promote interest in statistics: Effects on initial and deeper phases of interest development. *Journal of Educational Psychology.* https://doi.org/10.1037/edu0000921 [[pdf]](/publications/asher_harackiewicz_2024_jep.pdf)

**Asher, M. W.**, Sana, F., Koedinger, K.R., & Carvalho, P.F. (2024). Students can learn more efficiently when lectures are replaced with practice opportunities and feedback. *Proceedings of the Annual Meeting of the Cognitive Science Society, 46.* [[link]](https://escholarship.org/content/qt7p16r9xk/qt7p16r9xk_noSplash_5523aeea52976181855830ab0366c9f3.pdf?t=sfdr4y)

# 2023

**Asher, M. W.**, Harackiewicz, J. M., Beymer, P. N., Hecht, C. A., Lamont, L. B., Else-Quest, N. M., Priniski, S. J., Thoman, D. B., Hyde, J. S., & Smith, J. L. (2023). Utility-value intervention promotes persistence and diversity in STEM. *Proceedings of the National Academy of Sciences*. https://doi.org/10.1073/pnas.2300463120 [[pdf]](/publications/asher_et_al_2023_pnas.pdf)

Harackiewicz, J. M., Hecht, C. A., **Asher, M. W.**, Beymer, P. N., Lamont, L. B., Else-Quest, N. M., Priniski, S. J., Smith, J. L., Hyde, J. S., & Thoman, D. B. (2023). A prosocial value intervention in gateway STEM courses. *Journal of Personality and Social Psychology.* https://doi.org/10.1037/pspa0000356 [[pdf]](/publications/harackiewicz_et_al_2023_jpsp.pdf)

French, A. M., Else-Quest, N. M., **Asher, M. W.**, Thoman, D. B., Smith, J. L., Hyde, J. S., & Harackiewicz, J. M. (2023). An intersectional application of expectancy-value theory in an undergraduate chemistry course. *Psychology of Women Quarterly.* https://doi.org/10.1177/03616843231153390

Harackiewicz, J. M., & **Asher, M. W.** (2023). The utility value of a broad, comprehensive theory of motivation. *Motivation Science, 9*(1), 13–14. https://psycnet.apa.org/doi/10.1037/mot0000279

# 2021

Rosenzweig, E. Q., Hecht, C. A., Priniski, S. J., Canning, E. A., **Asher, M. W.**, Tibbetts, Y., Hyde, J. S., & Harackiewicz, J. M. (2021). Inside the STEM pipeline: Changes in students’ biomedical career plans across the college years. Science Advances, 7(18). https://doi.org/10.1126/sciadv.abe0985

Rosenzweig, E. Q., Harackiewicz, J. M., Hecht, C. A., Priniski, S. J., Canning, E. A., Tibbetts, Y., **Asher, M. W.**, & Hyde, J. S. (2021). College students’ reasons for leaving biomedical fields: Disenchantment with biomedicine or attraction to other fields? *Journal of Educational Psychology, 113*, 351–369. https://doi.org/10.1037/edu0000456

# 2013

Toner, K., Leary, M. R., **Asher, M. W.**, & Jongman-Sereno, K. P. (2013). Feeling superior is a bipartisan issue: Extremity (not direction) of political views predicts perceived belief superiority. *Psychological Science, 24*, 2454–2462. https://doi.org/10.1177/0956797613494848

